version: 0.2
phases:
  install:
    commands:
      - cd 01api
      - aws cloudformation package \
          --template petstore-api.yaml \
          --s3-bucket us-east-1-input-bucket \
          --output-template-file petstore-api-output.yaml 

artifacts:
  type: zip
  files:
    - 01api/petstore-api-output.yaml
